# ~/.config/starship.toml

# Use a minimal preset with compact info
add_newline = false

[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red)"

[git_branch]
symbol = "ğŸŒ± "

[git_status]
format = '([\[$all_status$ahead_behind\]](yellow) )'

[nodejs]
symbol = "ğŸŸ¢ "

[rust]
symbol = "ğŸ¦€ "

[python]
symbol = "ğŸ "